#!/bin/sh

# Spell check the commit message
if hash hunspell 2>/dev/null; then
  WORDS=$(hunspell -l < "$1")

  # Print commit message with all possible erroneous words highlighted
  if [ -n "$WORDS" ]; then
    echo -e "Possible spelling errors found in commit message:"
    echo -e "\e[1;30m$(egrep -w $(echo "$WORDS" | tr '\n' '|') "$1" --color=always | sed 's/\x1b\[m/\x1b\[1;30m/g')\e[0m"
    echo -e "Use git commit --amend to change the commit message."
  fi

else

  echo "hunspell does not appear to be installed"

fi
